# Generated by Django 4.2.4 on 2023-09-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='disc',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
